# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelDash', '0002_auto_20170224_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
