# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg', '0001_initial'),
        ('travelDash', '0003_auto_20170224_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loginReg.User'),
        ),
    ]
