# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelDash', '0007_auto_20170224_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_joined', to='travelDash.Trip'),
        ),
        migrations.AlterField(
            model_name='usertrip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_joined', to='loginReg.User'),
        ),
    ]
